language: node_js

node_js:
  - 'lts/dubnium'

before_install:
  - npm install --global npm

install:
  - npm install --no-optional

script:
  - npm run build:prod
  - npm test

deploy:
  provider: npm
  email: contact@cichol.com
  api_key:
    secure: "A4UUSuHIjB1jwpmOl3szhN1bBkIN0K98dPyWMai0vlBYraM/m1vJD0PBhdF0s3rfZcaJN+vqTGF3hab8NcqrTzooyt1KRqoOtJQZeWjtwXb8AGosLsBMdMdpa8jsbLwAGEmLY+iP99RFxaXoJgzs5a3UEwa/RU0xmNNSvuvab/nM/hKlMdn8nhChz6r4n5TmzDRPoKlkNdm3Gjfu7/Zj6GNTZiPUqCx6He0r+U0FDkWBmycqBf0qyyZm6SJeWPF8FaiMwQp5RTQV2aMILRNCvjzAtq3jUXmGqh2YRrM1TssK1cDK1sWdOxBR9Syad8DbxxbhT05ppWr98YczE1cQOZgxX/QbWUpVa85oqisMGdmBhaGfF2OHKvUpoxN8uXMhGw6Gz6psf01gZgZFprXCZs56VCgUDgGwIADxUUVi54HY0u9LfiSRJH5HXxzOoci/MGEJdPGGBQjUQOvgj+pztLtLvQSVWMEoBmceF/SVsog/WJ7HvL0QmZ8VR4eHB8MrKZZFR58PYAqEMdNOGnpTPA64hV6bJWnKn7ZIQsf0PI0Xp3LPYvJA6ZwAFTd5YGd4AGgWVFPnple8tD3m5Nu9+UbPG6tybAGccBE5KhHnzRoMpqQ+AjQpRIWd2Mt+qt97f0PunQmHJ822HjKXWjNPCkLPoAFCIB0SanD0YonJsjA="
  on:
    tags: true
    repo: epicinium/cognomen
    branch: master
  skip_cleanup: true
