language: node_js

node_js:
  - lts/dubnium

before_install:
  - npm install --global npm

install:
  - npm install --no-optional

script:
  - npm run build:prod
  - npm test

deploy:
  provider: npm
  email: contact@cichol.com
  api_key:
    secure: SkAbSNgQTLxxT1oTwM1lyLKUJcxlpsthxmsUwE9EDvB6WuXcFRRKv5OzOdofs4D3Mu0gtFV0VYIaG60Xzk/lawdySscc4lgkrvdVJU0nXEF2WcSNgHVTOYsSGEhtoSOpP9AfKqUMHs+A4yp3sPZ3LECqThhMqvOmyXktW8JV61TbF4r+Wq0RHOsq+tfWll5adSKqOmxjYDkD9Du/gtDbmhqbRlTorRGWUreO0Z4QZWCUvTPxhgPNetM0I7MFPNwlZeLGjPOJbXSuPpLkw7t0KIGgpguCcddMzVSa/d/Y2M0KtaxnIaAkp/V1hrZ2GfYRTSAuh2vBqVRXpDH60d5SxoPQnF39MUBYN3Kh2lKZe/8AZaCRmHihHD4AepsgTKoos1PFygFXfemNPFFeWbh3LkFmYbRzagII2dsmrQKVAJ1+cVih4pZ7r5PR+lDjrqRX2b5Pd+5T3/BaxyxuqWkOA0w6me5sG8AvrICCAZ4O2pU0n6TAeEwYmrV3GzCigCLc3L6hhJVbVNIkUm0as/YUxEyPDfpM5sT5ErNc0Dhfbhv+wtNooNsW8JYaz4BnhLZJxBSYS2arNwMxL7N4487yUN3HTRamdrtq0sd+o9PXsemKvvTIyOqwIXXQBSgVCMFz544jm976P9xamnEst34gytoM2z1SQvVekAgBIERh0T4=
  on:
    tags: true
    repo: epicinium/cognomen
    branch: master
  skip_cleanup: true
