language: node_js

node_js:
  - lts/dubnium

before_install:
  - npm install --global npm

install:
  - npm install --no-optional

script:
  - npm run build:prod
  - npm test

deploy:
  provider: npm
  email: contact@cichol.com
  api_key:
    secure: CgOemPeyZ/ZukPOLDRAj+7pdns9MpavQbE3nBT5tr/GnHratyOMZ74LBUm9d5yLC8EDjOyLKi419YQnNmrI/fELT+dQP8S6zcUhz/DHnEo84cta7MwG6L8zV9REP8reODg9VJgqKaGb45DoFMuG5vhxzQqXkoD4RbT7wLKkRrqggEiZHBKYppNmG3RjoQnAnqBwgOSwnjXVS85ioENYc1l8ezNmoaEOtpobvBoCz2yo1jNBw2fh9+sY4cWBJykFdyKCD7fwtRDhLdl+B7dut4hFL8/+36rdlPk971UYrSbeUsRCbJ1Xy1NdOsESaCGGc8DhSa7Tdg/orAV9LIwb+FTskmx+crvYwCIh8i3kcUYP2oxVicnS+fbMERsUjuowNb5SYmC8xRWwHwrdZbKXhUG0bZWi+pXIXSTZyteeR7eyyJ032ZIRZaNF7wzOXUoi2ekypqtlNQsxVvmqdaYglBg30Wp0hq+rQhISzBhuKrrFM3+8uW6nFQOpK9re9qjEZRC22P9BD/zXBi1/ywAfsXs4tQ7AKQfPD3dSYymB2nwlpXCKMHgeN4oykwheHOjYuLf4xMWSoaWWNAMWUPbzhSUrB2KVBV9/TdsutYM1NSSf6zAh3alotNgUKoJQ7X5ajvQ8Aqh1PAUn9pNZtQjXbJU6jDMsLPmQrvM5mmq4Kx14=
  on:
    tags: true
    repo: epicinium/cognomen
    branch: master
  skip_cleanup: true
